/**
 * Export utilities for Unstuck
 * Generates markdown checklists and handles clipboard/download
 */

/**
 * Generate markdown export of the task breakdown
 * @param {string} taskSummary - Brief summary of the task
 * @param {string[]} steps - Array of step descriptions
 * @param {number[]} completedSteps - Array of completed step indices
 * @returns {string} Markdown formatted checklist
 */
export function exportAsMarkdown(taskSummary, steps, completedSteps = []) {
  const lines = [];

  lines.push(`# ${taskSummary}`);
  lines.push('');
  lines.push('*Generated by [Unstuck](https://github.com/awohletz/unstuck) - Break through task paralysis*');
  lines.push('');

  steps.forEach((step, index) => {
    const isCompleted = completedSteps.includes(index);
    const checkbox = isCompleted ? '[x]' : '[ ]';
    lines.push(`- ${checkbox} **Step ${index + 1}:** ${step}`);
  });

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push('*Each step is designed to take 15 minutes or less.*');

  return lines.join('\n');
}

/**
 * Copy text to clipboard with fallback for older browsers
 * @param {string} text - Text to copy
 * @returns {Promise<boolean>} Whether copy was successful
 */
export async function copyToClipboard(text) {
  try {
    // Modern async clipboard API
    if (navigator.clipboard && navigator.clipboard.writeText) {
      await navigator.clipboard.writeText(text);
      return true;
    }

    // Fallback for older browsers
    const textarea = document.createElement('textarea');
    textarea.value = text;
    textarea.style.position = 'fixed';
    textarea.style.left = '-9999px';
    textarea.style.top = '-9999px';
    document.body.appendChild(textarea);
    textarea.focus();
    textarea.select();

    const successful = document.execCommand('copy');
    document.body.removeChild(textarea);

    return successful;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    return false;
  }
}

/**
 * Download content as a file
 * @param {string} content - File content
 * @param {string} filename - Name for the downloaded file
 * @param {string} mimeType - MIME type of the file
 */
export function downloadAsFile(content, filename, mimeType = 'text/markdown') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  link.style.display = 'none';

  document.body.appendChild(link);
  link.click();

  // Clean up
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate a filename from the task summary
 * @param {string} taskSummary - Task summary to convert
 * @returns {string} Safe filename
 */
export function generateFilename(taskSummary) {
  // Convert to lowercase, replace spaces with hyphens, remove special chars
  const safeName = taskSummary
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .slice(0, 50) // Limit length
    .replace(/^-|-$/g, ''); // Remove leading/trailing hyphens

  return `${safeName || 'unstuck-task'}.md`;
}
